title: bluehorn07's Blog
author:
  name: bluehorn07
  email: bluehornblues@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  “Talk is cheap. Show me the code.”

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    github: bluehorn07
    instagram: hsy_bluehorn07
    # twitter: jekyllrb
    # facebook: jekyll
    # linkedin: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - search.md
  - topics/development.md
  - topics/mathematics.md
  - topics/computer-science.md
  - about.md

# Build settings
theme: minima

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown # kramdown is advanced version of markdown

highlighter: rouge # Jekyll only support 'rouge' syntax highlighter

# build option
# ref: https://yangeok.github.io/blog/2019/05/21/jekyll-caching.html
# incremental: true
# limit_posts: 5